sudo: required
git:
  depth: false
jobs:
  include:
    - stage: 'Tests' # naming the Tests stage
      name: 'Unit Tests' # names the first Tests stage job
      language: elixir
      elixir:
        - 1.8
      otp_release:
        - 21.0
      cache:
        directories:
          - _build
          - deps
          - assets/node_modules
      addons:
        chrome: stable
        postgresql: '9.6'
      services:
        - postgresql
      before_script:
        - psql -c 'create database app_template_test;' -U postgres
      install:
        - gem install coveralls-multi
        - mix local.hex --force
        - mix local.rebar --force
        - mix deps.get
        - npm install --prefix assets
      script:
        - MIX_ENV=test mix coveralls.json
        - npm test --prefix assets
        - coveralls-multi
    - stage: 'Tests'
      name: 'Integration Tests'
      language: elixir
      elixir:
        - 1.8
      otp_release:
        - 21.0
      cache:
        directories:
          - _build
          - deps
          - assets/node_modules
      addons:
        chrome: stable
        postgresql: '9.6'
      services:
        - postgresql
        - xvfb
      before_script:
        - psql -c 'create database app_template_test;' -U postgres
      before_install:
        - wget https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
        - unzip chromedriver_linux64.zip
        - sudo apt-get install libnss3
        - sudo cp chromedriver /usr/local/bin/.
        - sudo chmod +x /usr/local/bin/chromedriver
        - pip install --user awscli
        - export PATH=$PATH:$HOME/.local/bin
        - mkdir -p $HOME/src
        - wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar
        - nohup java -Dselenium.LOGGER.level=WARNING -jar selenium-server-standalone-2.48.2.jar > /dev/null 2>&1 &
        - chromedriver > /dev/null 2>&1 &
      install:
        - mix local.hex --force
        - mix local.rebar --force
        - mix deps.get
        - npm install --prefix assets
      script:
        - xvfb-run mix integration_tests
    - stage: deploy
      name: 'Deploy'
      if: branch = master
      script: skip
      deploy:
        - provider: deis
          controller: deis.prod.revelry.net
          app: app-template
          cli_version: v2.20.0
          username: '$DEIS_USERNAME'
          password: '$DEIS_PASSWORD'
          on:
            branch: master
      after_deploy:
        - ./deis run "_build/prod/rel/app_template/bin/app_template migrate" -a app-template
