# sudo: true
# dist: trusty
git:
  depth: false
services:
  - docker
env:
  global:
    - DOCKER_USERNAME=travis
jobs:
  include:
    - stage: 'Tests' # naming the Tests stage
      name: 'Unit Tests' # names the first Tests stage job
      language: elixir
      elixir:
        - 1.8
      otp_release:
        - 21.0
      cache:
        directories:
          - _build
          - deps
          - assets/node_modules
      addons:
        postgresql: '9.6'
      services:
        - postgresql
      before_script:
        - nvm install 12.4.0 && nvm use 12.4.0
        - psql -c 'create database app_template_test;' -U postgres
      install:
        - gem install coveralls-multi
        - mix local.hex --force
        - mix local.rebar --force
        - mix deps.get
        - cd assets
        - npm install
        - cd ..
      script:
        - MIX_ENV=test mix coveralls.json
        - cd assets
        - npm test
        - cd ..
        - coveralls-multi
    - stage: docker deploy
      if: branch = master
      script: skip
      before_deploy:
        - echo $DOCKER_PASSWORD | docker login harbor.revelry-prod.revelry.net -u $DOCKER_USERNAME --password-stdin
      deploy:
        provider: script
        script: bin/docker_pub library/app-template harbor.revelry-prod.revelry.net
        on:
          branch: master
