sudo: false
git:
  depth: false
jobs:
  include:
    - stage: 'Tests' # naming the Tests stage
      name: 'Unit Tests' # names the first Tests stage job
      language: elixir
      elixir:
        - 1.8
      otp_release:
        - 21.0
      cache:
        directories:
          - _build
          - deps
          - assets/node_modules
      addons:
        postgresql: '9.6'
      services:
        - postgresql
      before_script:
        - psql -c 'create database app_template_test;' -U postgres
      install:
        - mix local.hex --force
        - mix local.rebar --force
        - mix deps.get
        - cd assets
        - npm install
        - cd ..
      script:
        - mix test
        - cd assets
        - npm test
        - cd ..
    - stage: deploy
      name: 'Deploy'
      if: branch = master
      script: skip
      deploy:
        - provider: deis
          controller: deis.prod.revelry.net
          app: app-template
          cli_version: v2.20.0
          username: '$DEIS_USERNAME'
          password: '$DEIS_PASSWORD'
          on:
            branch: master
      after_deploy:
        - ./deis run "_build/prod/rel/app_template/bin/app_template migrate" -a app-template
